# HTML
# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  fetchDepth: 0
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'helloworld'
    organization: 'devops-tcs-team1'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'DevOps-TCS-Team1_helloworld-sample'
    cliProjectName: 'helloworld-sample'
    cliSources: '$(build.sourcesDirectory)'
    projectName: 'helloworld-sample'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(build.sourcesDirectory)'
    includeRootFolder: false
- task: PublishBuildArtifacts@1
#- script: echo Hello, world!
#  displayName: 'Run a one-line script'
- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
- task: dependency-check-build-task@6
  inputs:
    projectName: 'helloworld-sample'
    format: 'HTML'
- task: owaspzap@1
  inputs:
    threshold: '1000'
    scantype: 'targetedScan'
    url: 'https://github.com/GullapalliAngel/helloworld-sample/blob/main/style.css'